project_id = "hffsgxsiwlzwpuktogku"

[api]
enabled = true
# Remove or comment out the port since it's not used with the cloud services
# port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000000

[auth]
site_url = "http://localhost:3001"
additional_redirect_urls = ["http://localhost:3001"]
jwt_expiry = 36000

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_SECRET)"
redirect_uri = "https://hffsgxsiwlzwpuktogku.supabase.co/auth/v1/callback"

[auth.email]
double_confirm_changes = true
enable_confirmations = true
enable_signup = true

# Remove or comment out sections that define local ports
#[db]
#port = 54322

#[studio]
#port = 54323

#[analytics]
#enabled = true
#port = 54327
#vector_port = 54328
#backend = "postgres"
